image: Visual Studio 2017

environment:
  nodejs_version: "Stable"

platform:
  - x64

cache:
  - node_modules

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build_script: npm run vscode:prepublish

test: off
