image: Visual Studio 2017

environment:
  nodejs_version: "Current"
  GH_TOKEN:
    secure: zHm517HtzQikntPP4AF80e9uBxmq5jzW3/vPfQjDRcVG3V1ZXrLKdIHHeaVD7k28

  matrix:
    - nodejs_arch: x86
    - nodejs_arch: x64

shallow_clone: true

install:
  - ps: Install-Product node $env:nodejs_version $env:nodejs_arch
  - npm install -g yume-chan/greenkeeper-lockfile
  - npm install

before_build: greenkeeper-lockfile-update

build_script: node scripts/package.js

after_build: greenkeeper-lockfile-upload

test: off

artifacts:
  - path: vsix\*.vsix
    name: Extension Packages
    type: File
