image: Visual Studio 2017

environment:
  version: "Current"
  GH_TOKEN:
    secure: zHm517HtzQikntPP4AF80e9uBxmq5jzW3/vPfQjDRcVG3V1ZXrLKdIHHeaVD7k28

  matrix:
    - arch: x86
    - arch: x64

clone_depth: 2

install:
  - ps: Install-Product node $env:version $env:arch
  - npm install

build_script: node scripts/package.js

test: off

artifacts:
  - path: vsix\*.vsix
    name: Extension Packages
    type: File
