image: Visual Studio 2017

environment:
  matrix:
    - arch: x86
    - arch: x64

clone_depth: 2

install:
  - ps: Install-Product node Current $env:arch
  - npm install

build_script: node scripts/package.js

test: off

artifacts:
  - path: vsix\*.vsix
    name: Extension Packages
    type: File
