image: Visual Studio 2017

environment:
  version: "Current"

  matrix:
    - arch: x86
    - arch: x64

clone_depth: 2

install:
  - ps: Install-Product node $env:version $env:arch
  - npm install

build_script:
  - npm run vscode:prepublish
  - node scripts/package.js

test: off

artifacts:
  - path: vsix\*.vsix
    name: Extension Packages
    type: File
